import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "500",
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, roboto.className, "bg-cyan-50")}>
        <main className={"max-w-720 bg-white m-auto"}>{children}</main>
      </body>
    </html>
  );
}
